apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-app-frontend
  labels:
    app: k8s-demo-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30900
    port: 80
  selector:
    app: k8s-demo-app
    tier: frontend 
